services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "{{ traefik_web_port }}:80"
      - "{{ traefik_websecure_port }}:443"
      - "{{ traefik_dashboard_port }}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/config:ro
      - {{ automation_data_path }}/traefik:/data
      - ./logs:/logs
    environment:
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_INSECURE=true
      - CF_DNS_API_TOKEN={{ vault_cloudflare_api_token | default('') }}
    command:
      - --configFile=/config/traefik.yml
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`{{ subdomain_traefik }}.{{ domain_name }}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth@file"

networks:
  traefik-network:
    external: true

volumes:
  traefik-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: {{ automation_data_path }}/traefik